- name: Run a simple test (check server is up)
      run: |
        # تشغيل التطبيق في الخلفية
        docker run -d -p 5000:5000 --name test-app ${{ github.repository }}:latest

        # الانتظار 10 ثواني (ضروري للسماح لسيرفر Flask بالبدء)
        echo "Waiting 10 seconds for Flask server to start..."
        sleep 10

        # اختبار الاتصال بـ curl والتأكد من نجاحه
        curl --fail http://localhost:5000
